services:
  - docker
before_install:
  - docker build -t tarkesh2shar/client -f ./reactWebpackStarter/DockerFile.dev ./reactWebpackStarter
script:
  - docker run tarkesh2shar/client npm run test
after_success:
  - docker build -t tarkesh2shar/test-client ./reactWebpackStarter
  - docker build -t tarkesh2shar/test-nginx ./nginx
  - docker build -t tarkesh2shar/test-server ./server

  #login into docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tarkesh2shar/test-client
  - docker push tarkesh2shar/test-nginx
  - docker push tarkesh2shar/test-server
