services:
  - docker
before_install:
  # aws login
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  # aws login ends
  - docker build -t tarkesh2shar/client -f ./reactWebpackStarter/DockerFile.dev ./reactWebpackStarter
script:
  - docker run tarkesh2shar/client npm run test
  - eval $(aws ecr get-login --region ap-south-1 --no-include-email)
after_success:
  - docker build -t 887171905960.dkr.ecr.ap-south-1.amazonaws.com/test-client ./reactWebpackStarter
  - docker build -t 887171905960.dkr.ecr.ap-south-1.amazonaws.com/test-nginx ./nginx
  - docker build -t 887171905960.dkr.ecr.ap-south-1.amazonaws.com/test-server ./server
  - docker push 887171905960.dkr.ecr.ap-south-1.amazonaws.com/test-client
  - docker push 887171905960.dkr.ecr.ap-south-1.amazonaws.com/test-nginx
  - docker push 887171905960.dkr.ecr.ap-south-1.amazonaws.com/test-server
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-887171905960"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY
